

use ADHERER;
DBCC CHECKIDENT (Nation, RESEED, 0);
Insert into Nation(name) values(N'Kinh');
Insert into Nation(name) values(N'Tày');
Insert into Nation(name) values(N'Thái');
Insert into Nation(name) values(N'Mường');
Insert into Nation(name) values(N'Khmer');
Insert into Nation(name) values(N'Hoa');
Insert into Nation(name) values(N'Nùng  ');
Insert into Nation(name) values(N'Mông');
Insert into Nation(name) values(N'Dao');
Insert into Nation(name) values(N'Gia Rai');
Insert into Nation(name) values(N'Ê  Đê');
Insert into Nation(name) values(N'Ba Na');
Insert into Nation(name) values(N'Sán Chay ');
Insert into Nation(name) values(N'Chăm ');
Insert into Nation(name) values(N'Cơ Ho');
Insert into Nation(name) values(N'Xơ Đăng');
Insert into Nation(name) values(N'Sán Dìu');
Insert into Nation(name) values(N'Hrê');
Insert into Nation(name) values(N'RaGlay');
Insert into Nation(name) values(N'Mnông');
Insert into Nation(name) values(N'Thổ');
Insert into Nation(name) values(N'Xtiêng');
Insert into Nation(name) values(N'Khơ mú');
Insert into Nation(name) values(N'Bru Vân Kiều');
Insert into Nation(name) values(N'Cơ Tu');
Insert into Nation(name) values(N'Giáy');
Insert into Nation(name) values(N'Tà Ôi');
Insert into Nation(name) values(N'Mạ');
Insert into Nation(name) values(N'Giẻ-Triêng');
Insert into Nation(name) values(N'Co');
Insert into Nation(name) values(N'Chơ Ro');
Insert into Nation(name) values(N'Xinh Mun');
Insert into Nation(name) values(N'Hà Nhì');
Insert into Nation(name) values(N'Chu Ru');
Insert into Nation(name) values(N'Lào');
Insert into Nation(name) values(N'La Chí');
Insert into Nation(name) values(N'Kháng');
Insert into Nation(name) values(N'Phù Lá');
Insert into Nation(name) values(N'La Hủ');
Insert into Nation(name) values(N'La Ha');
Insert into Nation(name) values(N'Pà Thẻn');
Insert into Nation(name) values(N'Lự');
Insert into Nation(name) values(N'Ngái');
Insert into Nation(name) values(N'Chứt');
Insert into Nation(name) values(N'Lô Lô');
Insert into Nation(name) values(N'Mảng');
Insert into Nation(name) values(N'Cơ Lao');
Insert into Nation(name) values(N'Bố Y');
Insert into Nation(name) values(N'Cống');
Insert into Nation(name) values(N'Si La');
Insert into Nation(name) values(N'Pu Péo');
Insert into Nation(name) values(N'Rơ Măm');
Insert into Nation(name) values(N'Brâu');
Insert into Nation(name) values(N'Ơ Đu');
