-- ----------------------------
-- Table structure for devvn_quanhuyen
-- ----------------------------
DROP TABLE IF EXISTS devvn_quanhuyen;
CREATE TABLE devvn_quanhuyen (
  maqh nvarchar(5)  NOT NULL,
  name nvarchar(100) NOT NULL,
  type nvarchar(30)  NOT NULL,
  matp nvarchar(5)  NOT NULL,
  PRIMARY KEY (maqh)
);

-- ----------------------------
-- Records of devvn_quanhuyen
-- ----------------------------

INSERT INTO devvn_quanhuyen VALUES ('001' , N'Quận Ba Đình' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('002' , N'Quận Hoàn Kiếm' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('003' , N'Quận Tây Hồ' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('004' , N'Quận Long Biên' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('005' , N'Quận Cầu Giấy' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('006' , N'Quận Đống Đa' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('007' , N'Quận Hai Bà Trưng' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('008' , N'Quận Hoàng Mai' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('009' , N'Quận Thanh Xuân' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('016' , N'Huyện Sóc Sơn' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('017' , N'Huyện Đông Anh' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('018' , N'Huyện Gia Lâm' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('019' , N'Quận Nam Từ Liêm' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('020' , N'Huyện Thanh Trì' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('021' , N'Quận Bắc Từ Liêm' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('024' , N'Thành phố Hà Giang' , N'Thành phố' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('026' , N'Huyện Đồng Văn' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('027' , N'Huyện Mèo Vạc' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('028' , N'Huyện Yên Minh' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('029' , N'Huyện Quản Bạ' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('030' , N'Huyện Vị Xuyên' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('031' , N'Huyện Bắc Mê' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('032' , N'Huyện Hoàng Su Phì' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('033' , N'Huyện Xín Mần' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('034' , N'Huyện Bắc Quang' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('035' , N'Huyện Quang Bình' , N'Huyện' , N'02');
INSERT INTO devvn_quanhuyen VALUES ('040' , N'Thành phố Cao Bằng' , N'Thành phố' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('042' , N'Huyện Bảo Lâm' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('043' , N'Huyện Bảo Lạc' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('044' , N'Huyện Thông Nông' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('045' , N'Huyện Hà Quảng' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('046' , N'Huyện Trà Lĩnh' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('047' , N'Huyện Trùng Khánh' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('048' , N'Huyện Hạ Lang' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('049' , N'Huyện Quảng Uyên' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('050' , N'Huyện Phục Hoà' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('051' , N'Huyện Hoà An' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('052' , N'Huyện Nguyên Bình' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('053' , N'Huyện Thạch An' , N'Huyện' , N'04');
INSERT INTO devvn_quanhuyen VALUES ('058' , N'Thành Phố Bắc Kạn' , N'Thành phố' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('060' , N'Huyện Pác Nặm' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('061' , N'Huyện Ba Bể' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('062' , N'Huyện Ngân Sơn' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('063' , N'Huyện Bạch Thông' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('064' , N'Huyện Chợ Đồn' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('065' , N'Huyện Chợ Mới' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('066' , N'Huyện Na Rì' , N'Huyện' , N'06');
INSERT INTO devvn_quanhuyen VALUES ('070' , N'Thành phố Tuyên Quang' , N'Thành phố' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('071' , N'Huyện Lâm Bình' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('072' , N'Huyện Nà Hang' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('073' , N'Huyện Chiêm Hóa' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('074' , N'Huyện Hàm Yên' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('075' , N'Huyện Yên Sơn' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('076' , N'Huyện Sơn Dương' , N'Huyện' , N'08');
INSERT INTO devvn_quanhuyen VALUES ('080' , N'Thành phố Lào Cai' , N'Thành phố' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('082' , N'Huyện Bát Xát' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('083' , N'Huyện Mường Khương' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('084' , N'Huyện Si Ma Cai' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('085' , N'Huyện Bắc Hà' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('086' , N'Huyện Bảo Thắng' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('087' , N'Huyện Bảo Yên' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('088' , N'Huyện Sa Pa' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('089' , N'Huyện Văn Bàn' , N'Huyện' , N'10');
INSERT INTO devvn_quanhuyen VALUES ('094' , N'Thành phố Điện Biên Phủ' , N'Thành phố' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('095' , N'Thị Xã Mường Lay' , N'Thị xã' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('096' , N'Huyện Mường Nhé' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('097' , N'Huyện Mường Chà' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('098' , N'Huyện Tủa Chùa' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('099' , N'Huyện Tuần Giáo' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('100' , N'Huyện Điện Biên' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('101' , N'Huyện Điện Biên Đông' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('102' , N'Huyện Mường Ảng' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('103' , N'Huyện Nậm Pồ' , N'Huyện' , N'11');
INSERT INTO devvn_quanhuyen VALUES ('105' , N'Thành phố Lai Châu' , N'Thành phố' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('106' , N'Huyện Tam Đường' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('107' , N'Huyện Mường Tè' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('108' , N'Huyện Sìn Hồ' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('109' , N'Huyện Phong Thổ' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('110' , N'Huyện Than Uyên' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('111' , N'Huyện Tân Uyên' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('112' , N'Huyện Nậm Nhùn' , N'Huyện' , N'12');
INSERT INTO devvn_quanhuyen VALUES ('116' , N'Thành phố Sơn La' , N'Thành phố' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('118' , N'Huyện Quỳnh Nhai' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('119' , N'Huyện Thuận Châu' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('120' , N'Huyện Mường La' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('121' , N'Huyện Bắc Yên' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('122' , N'Huyện Phù Yên' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('123' , N'Huyện Mộc Châu' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('124' , N'Huyện Yên Châu' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('125' , N'Huyện Mai Sơn' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('126' , N'Huyện Sông Mã' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('127' , N'Huyện Sốp Cộp' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('128' , N'Huyện Vân Hồ' , N'Huyện' , N'14');
INSERT INTO devvn_quanhuyen VALUES ('132' , N'Thành phố Yên Bái' , N'Thành phố' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('133' , N'Thị xã Nghĩa Lộ' , N'Thị xã' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('135' , N'Huyện Lục Yên' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('136' , N'Huyện Văn Yên' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('137' , N'Huyện Mù Căng Chải' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('138' , N'Huyện Trấn Yên' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('139' , N'Huyện Trạm Tấu' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('140' , N'Huyện Văn Chấn' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('141' , N'Huyện Yên Bình' , N'Huyện' , N'15');
INSERT INTO devvn_quanhuyen VALUES ('148' , N'Thành phố Hòa Bình' , N'Thành phố' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('150' , N'Huyện Đà Bắc' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('151' , N'Huyện Kỳ Sơn' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('152' , N'Huyện Lương Sơn' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('153' , N'Huyện Kim Bôi' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('154' , N'Huyện Cao Phong' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('155' , N'Huyện Tân Lạc' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('156' , N'Huyện Mai Châu' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('157' , N'Huyện Lạc Sơn' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('158' , N'Huyện Yên Thủy' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('159' , N'Huyện Lạc Thủy' , N'Huyện' , N'17');
INSERT INTO devvn_quanhuyen VALUES ('164' , N'Thành phố Thái Nguyên' , N'Thành phố' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('165' , N'Thành phố Sông Công' , N'Thành phố' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('167' , N'Huyện Định Hóa' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('168' , N'Huyện Phú Lương' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('169' , N'Huyện Đồng Hỷ' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('170' , N'Huyện Võ Nhai' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('171' , N'Huyện Đại Từ' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('172' , N'Thị xã Phổ Yên' , N'Thị xã' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('173' , N'Huyện Phú Bình' , N'Huyện' , N'19');
INSERT INTO devvn_quanhuyen VALUES ('178' , N'Thành phố Lạng Sơn' , N'Thành phố' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('180' , N'Huyện Tràng Định' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('181' , N'Huyện Bình Gia' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('182' , N'Huyện Văn Lãng' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('183' , N'Huyện Cao Lộc' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('184' , N'Huyện Văn Quan' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('185' , N'Huyện Bắc Sơn' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('186' , N'Huyện Hữu Lũng' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('187' , N'Huyện Chi Lăng' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('188' , N'Huyện Lộc Bình' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('189' , N'Huyện Đình Lập' , N'Huyện' , N'20');
INSERT INTO devvn_quanhuyen VALUES ('193' , N'Thành phố Hạ Long' , N'Thành phố' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('194' , N'Thành phố Móng Cái' , N'Thành phố' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('195' , N'Thành phố Cẩm Phả' , N'Thành phố' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('196' , N'Thành phố Uông Bí' , N'Thành phố' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('198' , N'Huyện Bình Liêu' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('199' , N'Huyện Tiên Yên' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('200' , N'Huyện Đầm Hà' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('201' , N'Huyện Hải Hà' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('202' , N'Huyện Ba Chẽ' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('203' , N'Huyện Vân Đồn' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('204' , N'Huyện Hoành Bồ' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('205' , N'Thị xã Đông Triều' , N'Thị xã' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('206' , N'Thị xã Quảng Yên' , N'Thị xã' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('207' , N'Huyện Cô Tô' , N'Huyện' , N'22');
INSERT INTO devvn_quanhuyen VALUES ('213' , N'Thành phố Bắc Giang' , N'Thành phố' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('215' , N'Huyện Yên Thế' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('216' , N'Huyện Tân Yên' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('217' , N'Huyện Lạng Giang' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('218' , N'Huyện Lục Nam' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('219' , N'Huyện Lục Ngạn' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('220' , N'Huyện Sơn Động' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('221' , N'Huyện Yên Dũng' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('222' , N'Huyện Việt Yên' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('223' , N'Huyện Hiệp Hòa' , N'Huyện' , N'24');
INSERT INTO devvn_quanhuyen VALUES ('227' , N'Thành phố Việt Trì' , N'Thành phố' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('228' , N'Thị xã Phú Thọ' , N'Thị xã' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('230' , N'Huyện Đoan Hùng' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('231' , N'Huyện Hạ Hoà' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('232' , N'Huyện Thanh Ba' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('233' , N'Huyện Phù Ninh' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('234' , N'Huyện Yên Lập' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('235' , N'Huyện Cẩm Khê' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('236' , N'Huyện Tam Nông' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('237' , N'Huyện Lâm Thao' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('238' , N'Huyện Thanh Sơn' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('239' , N'Huyện Thanh Thuỷ' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('240' , N'Huyện Tân Sơn' , N'Huyện' , N'25');
INSERT INTO devvn_quanhuyen VALUES ('243' , N'Thành phố Vĩnh Yên' , N'Thành phố' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('244' , N'Thị xã Phúc Yên' , N'Thị xã' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('246' , N'Huyện Lập Thạch' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('247' , N'Huyện Tam Dương' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('248' , N'Huyện Tam Đảo' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('249' , N'Huyện Bình Xuyên' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('250' , N'Huyện Mê Linh' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('251' , N'Huyện Yên Lạc' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('252' , N'Huyện Vĩnh Tường' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('253' , N'Huyện Sông Lô' , N'Huyện' , N'26');
INSERT INTO devvn_quanhuyen VALUES ('256' , N'Thành phố Bắc Ninh' , N'Thành phố' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('258' , N'Huyện Yên Phong' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('259' , N'Huyện Quế Võ' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('260' , N'Huyện Tiên Du' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('261' , N'Thị xã Từ Sơn' , N'Thị xã' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('262' , N'Huyện Thuận Thành' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('263' , N'Huyện Gia Bình' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('264' , N'Huyện Lương Tài' , N'Huyện' , N'27');
INSERT INTO devvn_quanhuyen VALUES ('268' , N'Quận Hà Đông' , N'Quận' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('269' , N'Thị xã Sơn Tây' , N'Thị xã' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('271' , N'Huyện Ba Vì' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('272' , N'Huyện Phúc Thọ' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('273' , N'Huyện Đan Phượng' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('274' , N'Huyện Hoài Đức' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('275' , N'Huyện Quốc Oai' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('276' , N'Huyện Thạch Thất' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('277' , N'Huyện Chương Mỹ' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('278' , N'Huyện Thanh Oai' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('279' , N'Huyện Thường Tín' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('280' , N'Huyện Phú Xuyên' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('281' , N'Huyện Ứng Hòa' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('282' , N'Huyện Mỹ Đức' , N'Huyện' , N'01');
INSERT INTO devvn_quanhuyen VALUES ('288' , N'Thành phố Hải Dương' , N'Thành phố' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('290' , N'Thị xã Chí Linh' , N'Thị xã' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('291' , N'Huyện Nam Sách' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('292' , N'Huyện Kinh Môn' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('293' , N'Huyện Kim Thành' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('294' , N'Huyện Thanh Hà' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('295' , N'Huyện Cẩm Giàng' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('296' , N'Huyện Bình Giang' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('297' , N'Huyện Gia Lộc' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('298' , N'Huyện Tứ Kỳ' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('299' , N'Huyện Ninh Giang' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('300' , N'Huyện Thanh Miện' , N'Huyện' , N'30');
INSERT INTO devvn_quanhuyen VALUES ('303' , N'Quận Hồng Bàng' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('304' , N'Quận Ngô Quyền' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('305' , N'Quận Lê Chân' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('306' , N'Quận Hải An' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('307' , N'Quận Kiến An' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('308' , N'Quận Đồ Sơn' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('309' , N'Quận Dương Kinh' , N'Quận' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('311' , N'Huyện Thuỷ Nguyên' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('312' , N'Huyện An Dương' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('313' , N'Huyện An Lão' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('314' , N'Huyện Kiến Thuỵ' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('315' , N'Huyện Tiên Lãng' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('316' , N'Huyện Vĩnh Bảo' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('317' , N'Huyện Cát Hải' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('318' , N'Huyện Bạch Long Vĩ' , N'Huyện' , N'31');
INSERT INTO devvn_quanhuyen VALUES ('323' , N'Thành phố Hưng Yên' , N'Thành phố' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('325' , N'Huyện Văn Lâm' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('326' , N'Huyện Văn Giang' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('327' , N'Huyện Yên Mỹ' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('328' , N'Huyện Mỹ Hào' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('329' , N'Huyện Ân Thi' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('330' , N'Huyện Khoái Châu' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('331' , N'Huyện Kim Động' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('332' , N'Huyện Tiên Lữ' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('333' , N'Huyện Phù Cừ' , N'Huyện' , N'33');
INSERT INTO devvn_quanhuyen VALUES ('336' , N'Thành phố Thái Bình' , N'Thành phố' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('338' , N'Huyện Quỳnh Phụ' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('339' , N'Huyện Hưng Hà' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('340' , N'Huyện Đông Hưng' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('341' , N'Huyện Thái Thụy' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('342' , N'Huyện Tiền Hải' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('343' , N'Huyện Kiến Xương' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('344' , N'Huyện Vũ Thư' , N'Huyện' , N'34');
INSERT INTO devvn_quanhuyen VALUES ('347' , N'Thành phố Phủ Lý' , N'Thành phố' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('349' , N'Huyện Duy Tiên' , N'Huyện' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('350' , N'Huyện Kim Bảng' , N'Huyện' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('351' , N'Huyện Thanh Liêm' , N'Huyện' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('352' , N'Huyện Bình Lục' , N'Huyện' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('353' , N'Huyện Lý Nhân' , N'Huyện' , N'35');
INSERT INTO devvn_quanhuyen VALUES ('356' , N'Thành phố Nam Định' , N'Thành phố' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('358' , N'Huyện Mỹ Lộc' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('359' , N'Huyện Vụ Bản' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('360' , N'Huyện Ý Yên' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('361' , N'Huyện Nghĩa Hưng' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('362' , N'Huyện Nam Trực' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('363' , N'Huyện Trực Ninh' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('364' , N'Huyện Xuân Trường' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('365' , N'Huyện Giao Thủy' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('366' , N'Huyện Hải Hậu' , N'Huyện' , N'36');
INSERT INTO devvn_quanhuyen VALUES ('369' , N'Thành phố Ninh Bình' , N'Thành phố' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('370' , N'Thành phố Tam Điệp' , N'Thành phố' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('372' , N'Huyện Nho Quan' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('373' , N'Huyện Gia Viễn' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('374' , N'Huyện Hoa Lư' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('375' , N'Huyện Yên Khánh' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('376' , N'Huyện Kim Sơn' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('377' , N'Huyện Yên Mô' , N'Huyện' , N'37');
INSERT INTO devvn_quanhuyen VALUES ('380' , N'Thành phố Thanh Hóa' , N'Thành phố' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('381' , N'Thị xã Bỉm Sơn' , N'Thị xã' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('382' , N'Thị xã Sầm Sơn' , N'Thị xã' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('384' , N'Huyện Mường Lát' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('385' , N'Huyện Quan Hóa' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('386' , N'Huyện Bá Thước' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('387' , N'Huyện Quan Sơn' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('388' , N'Huyện Lang Chánh' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('389' , N'Huyện Ngọc Lặc' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('390' , N'Huyện Cẩm Thủy' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('391' , N'Huyện Thạch Thành' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('392' , N'Huyện Hà Trung' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('393' , N'Huyện Vĩnh Lộc' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('394' , N'Huyện Yên Định' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('395' , N'Huyện Thọ Xuân' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('396' , N'Huyện Thường Xuân' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('397' , N'Huyện Triệu Sơn' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('398' , N'Huyện Thiệu Hóa' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('399' , N'Huyện Hoằng Hóa' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('400' , N'Huyện Hậu Lộc' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('401' , N'Huyện Nga Sơn' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('402' , N'Huyện Như Xuân' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('403' , N'Huyện Như Thanh' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('404' , N'Huyện Nông Cống' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('405' , N'Huyện Đông Sơn' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('406' , N'Huyện Quảng Xương' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('407' , N'Huyện Tĩnh Gia' , N'Huyện' , N'38');
INSERT INTO devvn_quanhuyen VALUES ('412' , N'Thành phố Vinh' , N'Thành phố' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('413' , N'Thị xã Cửa Lò' , N'Thị xã' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('414' , N'Thị xã Thái Hoà' , N'Thị xã' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('415' , N'Huyện Quế Phong' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('416' , N'Huyện Quỳ Châu' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('417' , N'Huyện Kỳ Sơn' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('418' , N'Huyện Tương Dương' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('419' , N'Huyện Nghĩa Đàn' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('420' , N'Huyện Quỳ Hợp' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('421' , N'Huyện Quỳnh Lưu' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('422' , N'Huyện Con Cuông' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('423' , N'Huyện Tân Kỳ' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('424' , N'Huyện Anh Sơn' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('425' , N'Huyện Diễn Châu' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('426' , N'Huyện Yên Thành' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('427' , N'Huyện Đô Lương' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('428' , N'Huyện Thanh Chương' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('429' , N'Huyện Nghi Lộc' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('430' , N'Huyện Nam Đàn' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('431' , N'Huyện Hưng Nguyên' , N'Huyện' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('432' , N'Thị xã Hoàng Mai' , N'Thị xã' , N'40');
INSERT INTO devvn_quanhuyen VALUES ('436' , N'Thành phố Hà Tĩnh' , N'Thành phố' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('437' , N'Thị xã Hồng Lĩnh' , N'Thị xã' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('439' , N'Huyện Hương Sơn' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('440' , N'Huyện Đức Thọ' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('441' , N'Huyện Vũ Quang' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('442' , N'Huyện Nghi Xuân' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('443' , N'Huyện Can Lộc' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('444' , N'Huyện Hương Khê' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('445' , N'Huyện Thạch Hà' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('446' , N'Huyện Cẩm Xuyên' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('447' , N'Huyện Kỳ Anh' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('448' , N'Huyện Lộc Hà' , N'Huyện' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('449' , N'Thị xã Kỳ Anh' , N'Thị xã' , N'42');
INSERT INTO devvn_quanhuyen VALUES ('450' , N'Thành Phố Đồng Hới' , N'Thành phố' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('452' , N'Huyện Minh Hóa' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('453' , N'Huyện Tuyên Hóa' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('454' , N'Huyện Quảng Trạch' , N'Thị xã' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('455' , N'Huyện Bố Trạch' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('456' , N'Huyện Quảng Ninh' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('457' , N'Huyện Lệ Thủy' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('458' , N'Thị xã Ba Đồn' , N'Huyện' , N'44');
INSERT INTO devvn_quanhuyen VALUES ('461' , N'Thành phố Đông Hà' , N'Thành phố' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('462' , N'Thị xã Quảng Trị' , N'Thị xã' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('464' , N'Huyện Vĩnh Linh' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('465' , N'Huyện Hướng Hóa' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('466' , N'Huyện Gio Linh' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('467' , N'Huyện Đa Krông' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('468' , N'Huyện Cam Lộ' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('469' , N'Huyện Triệu Phong' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('470' , N'Huyện Hải Lăng' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('471' , N'Huyện Cồn Cỏ' , N'Huyện' , N'45');
INSERT INTO devvn_quanhuyen VALUES ('474' , N'Thành phố Huế' , N'Thành phố' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('476' , N'Huyện Phong Điền' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('477' , N'Huyện Quảng Điền' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('478' , N'Huyện Phú Vang' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('479' , N'Thị xã Hương Thủy' , N'Thị xã' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('480' , N'Thị xã Hương Trà' , N'Thị xã' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('481' , N'Huyện A Lưới' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('482' , N'Huyện Phú Lộc' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('483' , N'Huyện Nam Đông' , N'Huyện' , N'46');
INSERT INTO devvn_quanhuyen VALUES ('490' , N'Quận Liên Chiểu' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('491' , N'Quận Thanh Khê' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('492' , N'Quận Hải Châu' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('493' , N'Quận Sơn Trà' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('494' , N'Quận Ngũ Hành Sơn' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('495' , N'Quận Cẩm Lệ' , N'Quận' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('497' , N'Huyện Hòa Vang' , N'Huyện' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('498' , N'Huyện Hoàng Sa' , N'Huyện' , N'48');
INSERT INTO devvn_quanhuyen VALUES ('502' , N'Thành phố Tam Kỳ' , N'Thành phố' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('503' , N'Thành phố Hội An' , N'Thành phố' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('504' , N'Huyện Tây Giang' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('505' , N'Huyện Đông Giang' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('506' , N'Huyện Đại Lộc' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('507' , N'Thị xã Điện Bàn' , N'Thị xã' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('508' , N'Huyện Duy Xuyên' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('509' , N'Huyện Quế Sơn' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('510' , N'Huyện Nam Giang' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('511' , N'Huyện Phước Sơn' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('512' , N'Huyện Hiệp Đức' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('513' , N'Huyện Thăng Bình' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('514' , N'Huyện Tiên Phước' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('515' , N'Huyện Bắc Trà My' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('516' , N'Huyện Nam Trà My' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('517' , N'Huyện Núi Thành' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('518' , N'Huyện Phú Ninh' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('519' , N'Huyện Nông Sơn' , N'Huyện' , N'49');
INSERT INTO devvn_quanhuyen VALUES ('522' , N'Thành phố Quảng Ngãi' , N'Thành phố' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('524' , N'Huyện Bình Sơn' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('525' , N'Huyện Trà Bồng' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('526' , N'Huyện Tây Trà' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('527' , N'Huyện Sơn Tịnh' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('528' , N'Huyện Tư Nghĩa' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('529' , N'Huyện Sơn Hà' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('530' , N'Huyện Sơn Tây' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('531' , N'Huyện Minh Long' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('532' , N'Huyện Nghĩa Hành' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('533' , N'Huyện Mộ Đức' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('534' , N'Huyện Đức Phổ' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('535' , N'Huyện Ba Tơ' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('536' , N'Huyện Lý Sơn' , N'Huyện' , N'51');
INSERT INTO devvn_quanhuyen VALUES ('540' , N'Thành phố Qui Nhơn' , N'Thành phố' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('542' , N'Huyện An Lão' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('543' , N'Huyện Hoài Nhơn' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('544' , N'Huyện Hoài Ân' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('545' , N'Huyện Phù Mỹ' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('546' , N'Huyện Vĩnh Thạnh' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('547' , N'Huyện Tây Sơn' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('548' , N'Huyện Phù Cát' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('549' , N'Thị xã An Nhơn' , N'Thị xã' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('550' , N'Huyện Tuy Phước' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('551' , N'Huyện Vân Canh' , N'Huyện' , N'52');
INSERT INTO devvn_quanhuyen VALUES ('555' , N'Thành phố Tuy Hoà' , N'Thành phố' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('557' , N'Thị xã Sông Cầu' , N'Thị xã' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('558' , N'Huyện Đồng Xuân' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('559' , N'Huyện Tuy An' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('560' , N'Huyện Sơn Hòa' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('561' , N'Huyện Sông Hinh' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('562' , N'Huyện Tây Hoà' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('563' , N'Huyện Phú Hoà' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('564' , N'Huyện Đông Hòa' , N'Huyện' , N'54');
INSERT INTO devvn_quanhuyen VALUES ('568' , N'Thành phố Nha Trang' , N'Thành phố' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('569' , N'Thành phố Cam Ranh' , N'Thành phố' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('570' , N'Huyện Cam Lâm' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('571' , N'Huyện Vạn Ninh' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('572' , N'Thị xã Ninh Hòa' , N'Thị xã' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('573' , N'Huyện Khánh Vĩnh' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('574' , N'Huyện Diên Khánh' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('575' , N'Huyện Khánh Sơn' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('576' , N'Huyện Trường Sa' , N'Huyện' , N'56');
INSERT INTO devvn_quanhuyen VALUES ('582' , N'Thành phố Phan Rang-Tháp Chàm' , N'Thành phố' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('584' , N'Huyện Bác Ái' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('585' , N'Huyện Ninh Sơn' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('586' , N'Huyện Ninh Hải' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('587' , N'Huyện Ninh Phước' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('588' , N'Huyện Thuận Bắc' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('589' , N'Huyện Thuận Nam' , N'Huyện' , N'58');
INSERT INTO devvn_quanhuyen VALUES ('593' , N'Thành phố Phan Thiết' , N'Thành phố' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('594' , N'Thị xã La Gi' , N'Thị xã' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('595' , N'Huyện Tuy Phong' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('596' , N'Huyện Bắc Bình' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('597' , N'Huyện Hàm Thuận Bắc' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('598' , N'Huyện Hàm Thuận Nam' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('599' , N'Huyện Tánh Linh' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('600' , N'Huyện Đức Linh' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('601' , N'Huyện Hàm Tân' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('602' , N'Huyện Phú Quí' , N'Huyện' , N'60');
INSERT INTO devvn_quanhuyen VALUES ('608' , N'Thành phố Kon Tum' , N'Thành phố' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('610' , N'Huyện Đắk Glei' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('611' , N'Huyện Ngọc Hồi' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('612' , N'Huyện Đắk Tô' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('613' , N'Huyện Kon Plông' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('614' , N'Huyện Kon Rẫy' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('615' , N'Huyện Đắk Hà' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('616' , N'Huyện Sa Thầy' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('617' , N'Huyện Tu Mơ Rông' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('618' , N'Huyện Ia H Drai' , N'Huyện' , N'62');
INSERT INTO devvn_quanhuyen VALUES ('622' , N'Thành phố Pleiku' , N'Thành phố' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('623' , N'Thị xã An Khê' , N'Thị xã' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('624' , N'Thị xã Ayun Pa' , N'Thị xã' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('625' , N'Huyện KBang' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('626' , N'Huyện Đăk Đoa' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('627' , N'Huyện Chư Păh' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('628' , N'Huyện Ia Grai' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('629' , N'Huyện Mang Yang' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('630' , N'Huyện Kông Chro' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('631' , N'Huyện Đức Cơ' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('632' , N'Huyện Chư Prông' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('633' , N'Huyện Chư Sê' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('634' , N'Huyện Đăk Pơ' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('635' , N'Huyện Ia Pa' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('637' , N'Huyện Krông Pa' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('638' , N'Huyện Phú Thiện' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('639' , N'Huyện Chư Pưh' , N'Huyện' , N'64');
INSERT INTO devvn_quanhuyen VALUES ('643' , N'Thành phố Buôn Ma Thuột' , N'Thành phố' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('644' , N'Thị Xã Buôn Hồ' , N'Thị xã' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('645' , N'Huyện Ea Hleo' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('646' , N'Huyện Ea Súp' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('647' , N'Huyện Buôn Đôn' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('648' , N'Huyện Cư Mgar' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('649' , N'Huyện Krông Búk' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('650' , N'Huyện Krông Năng' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('651' , N'Huyện Ea Kar' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('652' , N'Huyện M Đrắk' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('653' , N'Huyện Krông Bông' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('654' , N'Huyện Krông Pắc' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('655' , N'Huyện Krông A Na' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('656' , N'Huyện Lắk' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('657' , N'Huyện Cư Kuin' , N'Huyện' , N'66');
INSERT INTO devvn_quanhuyen VALUES ('660' , N'Thị xã Gia Nghĩa' , N'Thị xã' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('661' , N'Huyện Đăk Glong' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('662' , N'Huyện Cư Jút' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('663' , N'Huyện Đắk Mil' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('664' , N'Huyện Krông Nô' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('665' , N'Huyện Đắk Song' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('666' , N'Huyện Đắk RLấp' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('667' , N'Huyện Tuy Đức' , N'Huyện' , N'67');
INSERT INTO devvn_quanhuyen VALUES ('672' , N'Thành phố Đà Lạt' , N'Thành phố' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('673' , N'Thành phố Bảo Lộc' , N'Thành phố' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('674' , N'Huyện Đam Rông' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('675' , N'Huyện Lạc Dương' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('676' , N'Huyện Lâm Hà' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('677' , N'Huyện Đơn Dương' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('678' , N'Huyện Đức Trọng' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('679' , N'Huyện Di Linh' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('680' , N'Huyện Bảo Lâm' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('681' , N'Huyện Đạ Huoai' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('682' , N'Huyện Đạ Tẻh' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('683' , N'Huyện Cát Tiên' , N'Huyện' , N'68');
INSERT INTO devvn_quanhuyen VALUES ('688' , N'Thị xã Phước Long' , N'Thị xã' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('689' , N'Thị xã Đồng Xoài' , N'Thị xã' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('690' , N'Thị xã Bình Long' , N'Thị xã' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('691' , N'Huyện Bù Gia Mập' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('692' , N'Huyện Lộc Ninh' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('693' , N'Huyện Bù Đốp' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('694' , N'Huyện Hớn Quản' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('695' , N'Huyện Đồng Phú' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('696' , N'Huyện Bù Đăng' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('697' , N'Huyện Chơn Thành' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('698' , N'Huyện Phú Riềng' , N'Huyện' , N'70');
INSERT INTO devvn_quanhuyen VALUES ('703' , N'Thành phố Tây Ninh' , N'Thành phố' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('705' , N'Huyện Tân Biên' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('706' , N'Huyện Tân Châu' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('707' , N'Huyện Dương Minh Châu' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('708' , N'Huyện Châu Thành' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('709' , N'Huyện Hòa Thành' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('710' , N'Huyện Gò Dầu' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('711' , N'Huyện Bến Cầu' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('712' , N'Huyện Trảng Bàng' , N'Huyện' , N'72');
INSERT INTO devvn_quanhuyen VALUES ('718' , N'Thành phố Thủ Dầu Một' , N'Thành phố' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('719' , N'Huyện Bàu Bàng' , N'Huyện' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('720' , N'Huyện Dầu Tiếng' , N'Huyện' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('721' , N'Thị xã Bến Cát' , N'Thị xã' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('722' , N'Huyện Phú Giáo' , N'Huyện' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('723' , N'Thị xã Tân Uyên' , N'Thị xã' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('724' , N'Thị xã Dĩ An' , N'Thị xã' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('725' , N'Thị xã Thuận An' , N'Thị xã' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('726' , N'Huyện Bắc Tân Uyên' , N'Huyện' , N'74');
INSERT INTO devvn_quanhuyen VALUES ('731' , N'Thành phố Biên Hòa' , N'Thành phố' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('732' , N'Thị xã Long Khánh' , N'Thị xã' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('734' , N'Huyện Tân Phú' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('735' , N'Huyện Vĩnh Cửu' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('736' , N'Huyện Định Quán' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('737' , N'Huyện Trảng Bom' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('738' , N'Huyện Thống Nhất' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('739' , N'Huyện Cẩm Mỹ' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('740' , N'Huyện Long Thành' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('741' , N'Huyện Xuân Lộc' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('742' , N'Huyện Nhơn Trạch' , N'Huyện' , N'75');
INSERT INTO devvn_quanhuyen VALUES ('747' , N'Thành phố Vũng Tàu' , N'Thành phố' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('748' , N'Thành phố Bà Rịa' , N'Thành phố' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('750' , N'Huyện Châu Đức' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('751' , N'Huyện Xuyên Mộc' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('752' , N'Huyện Long Điền' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('753' , N'Huyện Đất Đỏ' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('754' , N'Huyện Tân Thành' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('755' , N'Huyện Côn Đảo' , N'Huyện' , N'77');
INSERT INTO devvn_quanhuyen VALUES ('760' , N'Quận 1' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('761' , N'Quận 12' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('762' , N'Quận Thủ Đức' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('763' , N'Quận 9' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('764' , N'Quận Gò Vấp' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('765' , N'Quận Bình Thạnh' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('766' , N'Quận Tân Bình' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('767' , N'Quận Tân Phú' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('768' , N'Quận Phú Nhuận' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('769' , N'Quận 2' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('770' , N'Quận 3' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('771' , N'Quận 10' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('772' , N'Quận 11' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('773' , N'Quận 4' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('774' , N'Quận 5' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('775' , N'Quận 6' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('776' , N'Quận 8' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('777' , N'Quận Bình Tân' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('778' , N'Quận 7' , N'Quận' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('783' , N'Huyện Củ Chi' , N'Huyện' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('784' , N'Huyện Hóc Môn' , N'Huyện' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('785' , N'Huyện Bình Chánh' , N'Huyện' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('786' , N'Huyện Nhà Bè' , N'Huyện' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('787' , N'Huyện Cần Giờ' , N'Huyện' , N'79');
INSERT INTO devvn_quanhuyen VALUES ('794' , N'Thành phố Tân An' , N'Thành phố' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('795' , N'Thị xã Kiến Tường' , N'Thị xã' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('796' , N'Huyện Tân Hưng' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('797' , N'Huyện Vĩnh Hưng' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('798' , N'Huyện Mộc Hóa' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('799' , N'Huyện Tân Thạnh' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('800' , N'Huyện Thạnh Hóa' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('801' , N'Huyện Đức Huệ' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('802' , N'Huyện Đức Hòa' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('803' , N'Huyện Bến Lức' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('804' , N'Huyện Thủ Thừa' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('805' , N'Huyện Tân Trụ' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('806' , N'Huyện Cần Đước' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('807' , N'Huyện Cần Giuộc' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('808' , N'Huyện Châu Thành' , N'Huyện' , N'80');
INSERT INTO devvn_quanhuyen VALUES ('815' , N'Thành phố Mỹ Tho' , N'Thành phố' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('816' , N'Thị xã Gò Công' , N'Thị xã' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('817' , N'Thị xã Cai Lậy' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('818' , N'Huyện Tân Phước' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('819' , N'Huyện Cái Bè' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('820' , N'Huyện Cai Lậy' , N'Thị xã' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('821' , N'Huyện Châu Thành' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('822' , N'Huyện Chợ Gạo' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('823' , N'Huyện Gò Công Tây' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('824' , N'Huyện Gò Công Đông' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('825' , N'Huyện Tân Phú Đông' , N'Huyện' , N'82');
INSERT INTO devvn_quanhuyen VALUES ('829' , N'Thành phố Bến Tre' , N'Thành phố' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('831' , N'Huyện Châu Thành' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('832' , N'Huyện Chợ Lách' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('833' , N'Huyện Mỏ Cày Nam' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('834' , N'Huyện Giồng Trôm' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('835' , N'Huyện Bình Đại' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('836' , N'Huyện Ba Tri' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('837' , N'Huyện Thạnh Phú' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('838' , N'Huyện Mỏ Cày Bắc' , N'Huyện' , N'83');
INSERT INTO devvn_quanhuyen VALUES ('842' , N'Thành phố Trà Vinh' , N'Thành phố' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('844' , N'Huyện Càng Long' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('845' , N'Huyện Cầu Kè' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('846' , N'Huyện Tiểu Cần' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('847' , N'Huyện Châu Thành' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('848' , N'Huyện Cầu Ngang' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('849' , N'Huyện Trà Cú' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('850' , N'Huyện Duyên Hải' , N'Huyện' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('851' , N'Thị xã Duyên Hải' , N'Thị xã' , N'84');
INSERT INTO devvn_quanhuyen VALUES ('855' , N'Thành phố Vĩnh Long' , N'Thành phố' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('857' , N'Huyện Long Hồ' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('858' , N'Huyện Mang Thít' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('859' , N'Huyện  Vũng Liêm' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('860' , N'Huyện Tam Bình' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('861' , N'Thị xã Bình Minh' , N'Thị xã' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('862' , N'Huyện Trà Ôn' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('863' , N'Huyện Bình Tân' , N'Huyện' , N'86');
INSERT INTO devvn_quanhuyen VALUES ('866' , N'Thành phố Cao Lãnh' , N'Thành phố' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('867' , N'Thành phố Sa Đéc' , N'Thành phố' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('868' , N'Thị xã Hồng Ngự' , N'Thị xã' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('869' , N'Huyện Tân Hồng' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('870' , N'Huyện Hồng Ngự' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('871' , N'Huyện Tam Nông' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('872' , N'Huyện Tháp Mười' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('873' , N'Huyện Cao Lãnh' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('874' , N'Huyện Thanh Bình' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('875' , N'Huyện Lấp Vò' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('876' , N'Huyện Lai Vung' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('877' , N'Huyện Châu Thành' , N'Huyện' , N'87');
INSERT INTO devvn_quanhuyen VALUES ('883' , N'Thành phố Long Xuyên' , N'Thành phố' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('884' , N'Thành phố Châu Đốc' , N'Thành phố' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('886' , N'Huyện An Phú' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('887' , N'Thị xã Tân Châu' , N'Thị xã' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('888' , N'Huyện Phú Tân' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('889' , N'Huyện Châu Phú' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('890' , N'Huyện Tịnh Biên' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('891' , N'Huyện Tri Tôn' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('892' , N'Huyện Châu Thành' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('893' , N'Huyện Chợ Mới' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('894' , N'Huyện Thoại Sơn' , N'Huyện' , N'89');
INSERT INTO devvn_quanhuyen VALUES ('899' , N'Thành phố Rạch Giá' , N'Thành phố' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('900' , N'Thị xã Hà Tiên' , N'Thị xã' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('902' , N'Huyện Kiên Lương' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('903' , N'Huyện Hòn Đất' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('904' , N'Huyện Tân Hiệp' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('905' , N'Huyện Châu Thành' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('906' , N'Huyện Giồng Riềng' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('907' , N'Huyện Gò Quao' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('908' , N'Huyện An Biên' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('909' , N'Huyện An Minh' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('910' , N'Huyện Vĩnh Thuận' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('911' , N'Huyện Phú Quốc' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('912' , N'Huyện Kiên Hải' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('913' , N'Huyện U Minh Thượng' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('914' , N'Huyện Giang Thành' , N'Huyện' , N'91');
INSERT INTO devvn_quanhuyen VALUES ('916' , N'Quận Ninh Kiều' , N'Quận' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('917' , N'Quận Ô Môn' , N'Quận' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('918' , N'Quận Bình Thuỷ' , N'Quận' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('919' , N'Quận Cái Răng' , N'Quận' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('923' , N'Quận Thốt Nốt' , N'Quận' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('924' , N'Huyện Vĩnh Thạnh' , N'Huyện' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('925' , N'Huyện Cờ Đỏ' , N'Huyện' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('926' , N'Huyện Phong Điền' , N'Huyện' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('927' , N'Huyện Thới Lai' , N'Huyện' , N'92');
INSERT INTO devvn_quanhuyen VALUES ('930' , N'Thành phố Vị Thanh' , N'Thành phố' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('931' , N'Thị xã Ngã Bảy' , N'Thị xã' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('932' , N'Huyện Châu Thành A' , N'Huyện' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('933' , N'Huyện Châu Thành' , N'Huyện' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('934' , N'Huyện Phụng Hiệp' , N'Huyện' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('935' , N'Huyện Vị Thuỷ' , N'Huyện' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('936' , N'Huyện Long Mỹ' , N'Huyện' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('937' , N'Thị xã Long Mỹ' , N'Thị xã' , N'93');
INSERT INTO devvn_quanhuyen VALUES ('941' , N'Thành phố Sóc Trăng' , N'Thành phố' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('942' , N'Huyện Châu Thành' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('943' , N'Huyện Kế Sách' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('944' , N'Huyện Mỹ Tú' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('945' , N'Huyện Cù Lao Dung' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('946' , N'Huyện Long Phú' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('947' , N'Huyện Mỹ Xuyên' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('948' , N'Thị xã Ngã Năm' , N'Thị xã' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('949' , N'Huyện Thạnh Trị' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('950' , N'Thị xã Vĩnh Châu' , N'Thị xã' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('951' , N'Huyện Trần Đề' , N'Huyện' , N'94');
INSERT INTO devvn_quanhuyen VALUES ('954' , N'Thành phố Bạc Liêu' , N'Thành phố' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('956' , N'Huyện Hồng Dân' , N'Huyện' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('957' , N'Huyện Phước Long' , N'Huyện' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('958' , N'Huyện Vĩnh Lợi' , N'Huyện' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('959' , N'Thị xã Giá Rai' , N'Thị xã' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('960' , N'Huyện Đông Hải' , N'Huyện' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('961' , N'Huyện Hoà Bình' , N'Huyện' , N'95');
INSERT INTO devvn_quanhuyen VALUES ('964' , N'Thành phố Cà Mau' , N'Thành phố' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('966' , N'Huyện U Minh' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('967' , N'Huyện Thới Bình' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('968' , N'Huyện Trần Văn Thời' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('969' , N'Huyện Cái Nước' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('970' , N'Huyện Đầm Dơi' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('971' , N'Huyện Năm Căn' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('972' , N'Huyện Phú Tân' , N'Huyện' , N'96');
INSERT INTO devvn_quanhuyen VALUES ('973' , N'Huyện Ngọc Hiển' , N'Huyện' , N'96');

select count(maqh) from devvn_quanhuyen